### ISSUE TITLE
Logging: more friendly API for custom encoding of log message

### ISSUE THREAD

**Issue by gladko** [Devexperts/QD#5]
In order to log sanitisation, we need to modify log messages. For instance, replace '\n' symbol to '\\n'.
I'd like to delegate this work to dxLib DetailedLogLayout and LogFormatter classes.
`LogFormatter.format` public method uses LogFormatter.STRING_FORMAT_CONSUMER lambda for log msg encoding but I don't see any conventional way to override this field initialisation.
So to achieve my goal, I need to
- extend LogFormatter class and locate it in `com.devexperts.logging` package. 
- in this custom-LogFormatter, I need to override LogFormatter.format package-visible method where I would be able to use my own Msg encoder instead of default one.
- extend DetailedLogLayout class for using custom-LogFormatter

This seems too difficult for such a general needs.
Could you pls provide more friendly API for custom encoding.

**Comment by tsitelov** [comment]
Processed through the [customer support portal](https://jira.in.devexperts.com/servicedesk/customer/portal/1)
