### ISSUE TITLE
QD monitoring: getting CollectorCounters for striped collector

### ISSUE THREAD

**Issue by gladko** [Devexperts/QD#6]
Hi team.
Class com.devexperts.qd.impl.matrix.Collector has method `getCountersSinceStart` that returns CollectorCounters. These counters are very useful and help understand QDS usage.
But working with striped collector, receiving these counters becomes not a trivial task and requires creation utility class in `com.devexperts.qd.impl.stripe` package. 

I wonder if QDS library can provide some public monitoring API covering this functionality and supporting both regular and striped collectors.

PS: QDS internal com.devexperts.qd.monitoring.MonitoredQDEndpoint also does not support striped collectors. Method logCollectorCounters checks `collector instanceof Collector` class. StripedCollector fails this check. 
```
private void logCollectorCounters() {
        for (QDContract contract : QDContract.values()) {
            QDCollector collector = getCollector(contract);
            if (!(collector instanceof Collector))
                continue;

            ... // print CollectorCounters
        }
    }
```

**Comment by tsitelov** [comment]
Processed through the [customer support portal](https://jira.in.devexperts.com/servicedesk/customer/portal/1)
