### ISSUE TITLE
QD monitoring: QDStats graph is broken for striped collector

### ISSUE THREAD

**Issue by gladko** [Devexperts/QD#7]
Hi team.

In our application we have several StripedCollectors and we'd like to aggregate their monitoring info in a single QDStats instance.
Noticed the following issues (see attached debug screenshots):
1.  during creation a stripe, its stat is added twice to StripedCollector stat.  ![1  duplicates](https://github.com/devexperts/QD/assets/127444722/e41bf35a-b204-4644-9be8-832677dfcc6e)
2.  if I create second StripedCollector, then stripe stats of this collector are added to first StripedCollector.  ![2  wrong_parent](https://github.com/devexperts/QD/assets/127444722/96e22fa5-5c96-4759-968d-9996beda0587)

**Comment by tsitelov** [comment]
Processed through the [customer support portal](https://jira.in.devexperts.com/servicedesk/customer/portal/1)
