### ISSUE TITLE
Cannot build Project - artifact not found in dxfeed.jfrog.io

### ISSUE THREAD

**Issue by jrzabott** [Devexperts/QD#8]
When trying to build the project from scratch, it looks like the `dxfeed.jfrog.io` does not contain `jmxtools`.
Even when I set versions to 1.2 and 1.2.1 that are immediately available in public maven repos (public maven repository - https://mvnrepository.com/artifact/com.sun.jdmk/jmxtools/1.2.1), no luck.

Build also couldn't locate the specific version 1.2_8 or 1.2.8 as found in links, respectively:

- https://repository.liferay.com/nexus/content/repositories/public/com/sun/jdmk/jmxtools/1.2_8/
- http://nexus.emergya.es/nexus/content/repositories/public/com/sun/jdmk/jmxtools/1.2.8)/nexus/content/repositories/public/com/sun/jdmk/jmxtools/1.2.8 -- this one was unreachable when I tried to visit from browser.

**Comment by jrzabott** [comment]
```
[WARNING] Failed to download jmxtools-1.2_8.pom [https://dxfeed.jfrog.io/artifactory/maven-open/]
[WARNING] Failed to download jmxtools-1.2_8.pom [https://repo.maven.apache.org/maven2/]
[WARNING] The POM for com.sun.jdmk:jmxtools:jar:1.2_8 is missing, no dependency information available
[WARNING] Failed to download jmxtools-1.2_8.jar [https://dxfeed.jfrog.io/artifactory/maven-open/]
[WARNING] Failed to download jmxtools-1.2_8.jar [https://repo.maven.apache.org/maven2/]
Cannot resolve com.sun.jdmk:jmxtools:1.2_8

```

**Comment by tsitelov** [comment]
Required artifact can be found as part of Java Management Extension (JMX) 1.2.1 on Oracle's site: https://www.oracle.com/java/technologies/java-archive-downloads-java-plat-downloads.html 

You need to download [jmx-1_2_1-ri.zip](https://download.oracle.com/otn-pub/java/jmx/1.2.1-ri/jmx-1_2_1-ri.zip) from Oracle (requires Oracle account), extract `jmxtools.jar` from the lib section and deploy it to your local Maven repository with the expected Maven coordinates.

**Comment by rybak** [comment]
If you have Maven installed locally, the [commands to manually install the jar](https://stackoverflow.com/a/1872266/1083697) are:

```sh
$ cd path/to/unpackaged/zip
$ cd jmx-1_2_1-bin/lib
$ mvn install:install-file -Dfile=jmxtools.jar -DgroupId=com.sun.jdmk -DartifactId=jmxtools -Dversion=1.2.8 -Dpackaging=jar
```
